DECLARE @LT AS NUMERIC(10, 4);
SET @LT = (SELECT MAX(LAT_N) FROM STATION WHERE LAT_N < 137.2345)
SELECT CAST(ROUND(LONG_W, 4) AS NUMERIC(10, 4)) FROM STATION WHERE (CAST(LAT_N AS NUMERIC(10, 4))) = @LT