SELECT
    DISTINCT(CITY)
FROM
    STATION
WHERE
    SUBSTRING(CITY,LEN(CITY),1) = 'A' OR
    SUBSTRING(CITY,LEN(CITY),1) = 'E' OR
    SUBSTRING(CITY,LEN(CITY),1) = 'I' OR
    SUBSTRING(CITY,LEN(CITY),1) = 'O' OR
    SUBSTRING(CITY,LEN(CITY),1) = 'U' OR
    SUBSTRING(CITY,LEN(CITY),1) = 'a' OR
    SUBSTRING(CITY,LEN(CITY),1) = 'e' OR
    SUBSTRING(CITY,LEN(CITY),1) = 'i' OR
    SUBSTRING(CITY,LEN(CITY),1) = 'o' OR
    SUBSTRING(CITY,LEN(CITY),1) = 'u';